name = "fuyanya-temp-email"
main = "src/worker.ts"
compatibility_date = "2025-04-01"
compatibility_flags = [ "nodejs_compat" ]
keep_vars = true

[vars]
PREFIX = "tmp"
DEFAULT_DOMAINS = ["fuyanya.cloud"]
DOMAINS = ["fuyanya.cloud"]
JWT_SECRET = "fuyanya_temp_email_secret_2026_random_key_12345"
BLACK_LIST = ""
ENABLE_USER_CREATE_EMAIL = true
ENABLE_USER_DELETE_EMAIL = true
ENABLE_AUTO_REPLY = false

[[d1_databases]]
binding = "DB"
database_name = "fuyanya-temp-email-db"
database_id = "7188e47b-e440-438b-b1a2-af574b349d4f"